CI: Run pre-commit checks with prek, and post suggestions like main repo (#1622)

diff --git a/.github/workflows/additional_checks.yml b/.github/workflows/additional_checks.yml
--- a/.github/workflows/additional_checks.yml
+++ b/.github/workflows/additional_checks.yml
@@ -21,12 +21,14 @@ permissions: {}
 jobs:
   additional-checks:
     name: Additional checks
-    runs-on: ubuntu-latest
-    env:
-      # renovate: datasource=python-version depName=python
-      PYTHON_VERSION: "3.14"
+    runs-on: ubuntu-24.04
     permissions:
       contents: read
+    env:
+      # renovate: datasource=pypi depName=prek
+      PREK_VERSION: 0.3.1
+      # renovate: datasource=python-version depName=python
+      PYTHON_VERSION: "3.14"
 
     steps:
       - name: Checkout repository contents
@@ -39,5 +41,54 @@ jobs:
         uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
+      - name: Install uv and restore its cache
+        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
+        with:
+          enable-cache: false
+      - name: "Cache pre-commit/prek"
+        # Not used for releases, only for running pre-commit
+        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3  # zizmor: ignore[cache-poisoning]
+        with:
+          path: |-
+            ~/.cache/prek
+          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
+      - name: Install prek
+        run: uv tool install "prek@${PREK_VERSION}"
+      - name: "Run pre-commit/prek for fixes"
+        run: |
+          echo '```console' > "$GITHUB_STEP_SUMMARY"
+          # Enable color output for pre-commit and remove it for the summary
+          # Use --hook-stage=manual to enable slower pre-commit hooks that are skipped by default
+          # Skip hooks already handled in another workflow, to avoid duplicate suggestions
+          # Skip hooks with no fixes made with these hooks (for now)
+          prek run --all-files --show-diff-on-failure --color=always --hook-stage=manual \
+            --skip ruff-check --skip ruff-format \
+            --skip actionlint \
+            --skip editorconfig-checker \
+            --skip flake8 \
+            --skip yamllint | \
+            tee >(sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' >> "$GITHUB_STEP_SUMMARY") >&1
+          exit_code="${PIPESTATUS[0]}"
+          echo '```' >> "$GITHUB_STEP_SUMMARY"
+          exit "$exit_code"
 
-      - run: pip install pre-commit && pre-commit run -a
+      - name: Create and uploads code suggestions to apply for pre-commit
+        # Will fail fast here if there are changes required
+        id: diff-pre-commit
+        # To run after pre-commit step exits with failure
+        if: ${{ !cancelled() }}
+        uses: OSGeo/grass/.github/actions/create-upload-suggestions@main
+        with:
+          tool-name: pre-commit
+          # To keep repo's file structure in formatted changes artifact
+          extra-upload-changes: pyproject.toml
+      - name: "Run pre-commit/prek"
+        run: |
+          echo '```console' > "$GITHUB_STEP_SUMMARY"
+          # Enable color output for pre-commit and remove it for the summary
+          # Use --hook-stage=manual to enable slower pre-commit hooks that are skipped by default
+          prek run --all-files --show-diff-on-failure --color=always --hook-stage=manual | \
+            tee >(sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' >> "$GITHUB_STEP_SUMMARY") >&1
+          exit_code="${PIPESTATUS[0]}"
+          echo '```' >> "$GITHUB_STEP_SUMMARY"
+          exit "$exit_code"
